apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - env:
        - name: MAMONGO_HOST
          valueFrom:
            configMapKeyRef:
              key: MAMONGO_HOST
              name: db-env
        - name: MASQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MASQL_HOST
              name: db-env
        - name: MYSQL_DATABASE
          valueFrom:
            configMapKeyRef:
              key: MYSQL_DATABASE
              name: db-env
        - name: MYSQL_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASSWORD
              name: db-env
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: db-env
        image: phpmyadmin/phpmyadmin
        name: phpmyadmin
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  ports:
  - name: "8000"
    port: 8000
    targetPort: 80
  selector:
    app: phpmyadmin
status:
  loadBalancer: {}

